version: "3"
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: pyspark
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"

    expose:
      - "8888"
      - "4040"
      - "4041"
      - "4042"

    environment:
      #CHOWN_HOME: "yes"
      #GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      SPARK_OPTS: "--driver-java-options=-Xms16g --driver-java-options=-Xmx32g --driver-java-options=-Dlog4j.logLevel=info"
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
      - /Users/bpark/Projects/TCGA_Spark/work:/home/jovyan/work
      - /Users/bpark/Projects/TCGA_Spark/code:/home/jovyan/code
      - /Users/bpark/Projects/TCGA_Spark/data:/home/jovyan/data